/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as claimManagerStorageSol from "./ClaimManagerStorage.sol";
export type { claimManagerStorageSol };
