/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bounty from "./Bounty";
export type { bounty };
import type * as bountyFactory from "./BountyFactory";
export type { bountyFactory };
import type * as claimManager from "./ClaimManager";
export type { claimManager };
import type * as depositManager from "./DepositManager";
export type { depositManager };
import type * as kyc from "./KYC";
export type { kyc };
import type * as mocks from "./Mocks";
export type { mocks };
import type * as onlyOpenQ from "./OnlyOpenQ";
export type { onlyOpenQ };
import type * as openQ from "./OpenQ";
export type { openQ };
import type * as oracle from "./Oracle";
export type { oracle };
import type * as tokenWhitelist from "./TokenWhitelist";
export type { tokenWhitelist };
