/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as transferFeeTokenSol from "./TransferFeeToken.sol";
export type { transferFeeTokenSol };
export type { MockDai } from "./MockDai";
export type { MockKyc } from "./MockKyc";
export type { MockLink } from "./MockLink";
export type { MockNft } from "./MockNft";
export type { TestToken } from "./TestToken";
