/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as atomicBountyStorageSol from "./AtomicBountyStorage.sol";
export type { atomicBountyStorageSol };
import type * as ongoingBountyStorageSol from "./OngoingBountyStorage.sol";
export type { ongoingBountyStorageSol };
import type * as tieredFixedBountyStorageSol from "./TieredFixedBountyStorage.sol";
export type { tieredFixedBountyStorageSol };
import type * as tieredPercentageBountyStorageSol from "./TieredPercentageBountyStorage.sol";
export type { tieredPercentageBountyStorageSol };
export type { BountyStorageCore } from "./BountyStorageCore";
export type { TieredBountyStorageCore } from "./TieredBountyStorageCore";
