/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as depositManagerStorageSol from "./DepositManagerStorage.sol";
export type { depositManagerStorageSol };
