/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export declare namespace OpenQDefinitions {
  export type InitOperationStruct = {
    operationType: PromiseOrValue<BigNumberish>;
    data: PromiseOrValue<BytesLike>;
  };

  export type InitOperationStructOutput = [number, string] & {
    operationType: number;
    data: string;
  };
}

export interface OpenQV1Interface extends utils.Interface {
  functions: {
    "VERSION_1()": FunctionFragment;
    "addressToExternalUserId(address)": FunctionFragment;
    "associateExternalIdToAddress(string,address)": FunctionFragment;
    "bountyAddressToBountyId(address)": FunctionFragment;
    "bountyFactory()": FunctionFragment;
    "bountyIdToAddress(string)": FunctionFragment;
    "bountyIsOpen(string)": FunctionFragment;
    "bountyType(string)": FunctionFragment;
    "claimManager()": FunctionFragment;
    "depositManager()": FunctionFragment;
    "externalUserIdToAddress(string)": FunctionFragment;
    "getImplementation()": FunctionFragment;
    "initialize(address,address,address,address)": FunctionFragment;
    "mintBounty(string,string,(uint32,bytes))": FunctionFragment;
    "oracle()": FunctionFragment;
    "owner()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setBountyFactory(address)": FunctionFragment;
    "setClaimManager(address)": FunctionFragment;
    "setDepositManager(address)": FunctionFragment;
    "setFundingGoal(string,address,uint256)": FunctionFragment;
    "setInvoiceComplete(string,bytes)": FunctionFragment;
    "setInvoiceRequired(string,bool)": FunctionFragment;
    "setKycRequired(string,bool)": FunctionFragment;
    "setPayoutScheduleFixed(string,uint256[],address)": FunctionFragment;
    "setSupportingDocumentsComplete(string,bytes)": FunctionFragment;
    "setSupportingDocumentsRequired(string,bool)": FunctionFragment;
    "setTierWinner(string,uint256,string)": FunctionFragment;
    "tierClaimed(string,uint256)": FunctionFragment;
    "transferOracle(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "VERSION_1"
      | "addressToExternalUserId"
      | "associateExternalIdToAddress"
      | "bountyAddressToBountyId"
      | "bountyFactory"
      | "bountyIdToAddress"
      | "bountyIsOpen"
      | "bountyType"
      | "claimManager"
      | "depositManager"
      | "externalUserIdToAddress"
      | "getImplementation"
      | "initialize"
      | "mintBounty"
      | "oracle"
      | "owner"
      | "proxiableUUID"
      | "renounceOwnership"
      | "setBountyFactory"
      | "setClaimManager"
      | "setDepositManager"
      | "setFundingGoal"
      | "setInvoiceComplete"
      | "setInvoiceRequired"
      | "setKycRequired"
      | "setPayoutScheduleFixed"
      | "setSupportingDocumentsComplete"
      | "setSupportingDocumentsRequired"
      | "setTierWinner"
      | "tierClaimed"
      | "transferOracle"
      | "transferOwnership"
      | "upgradeTo"
      | "upgradeToAndCall"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "VERSION_1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addressToExternalUserId",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "associateExternalIdToAddress",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "bountyAddressToBountyId",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "bountyFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bountyIdToAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "bountyIsOpen",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "bountyType",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "externalUserIdToAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBounty",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      OpenQDefinitions.InitOperationStruct
    ]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBountyFactory",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFundingGoal",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setInvoiceComplete",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setInvoiceRequired",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setKycRequired",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPayoutScheduleFixed",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupportingDocumentsComplete",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupportingDocumentsRequired",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setTierWinner",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tierClaimed",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOracle",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "VERSION_1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addressToExternalUserId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "associateExternalIdToAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bountyAddressToBountyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bountyFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bountyIdToAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bountyIsOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bountyType", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "externalUserIdToAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintBounty", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBountyFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFundingGoal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInvoiceComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInvoiceRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKycRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPayoutScheduleFixed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupportingDocumentsComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupportingDocumentsRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTierWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tierClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "BountyClosed(string,address,string,address,uint256,uint256,bytes,uint256)": EventFragment;
    "BountyCreated(string,string,address,address,uint256,uint256,bytes,uint256)": EventFragment;
    "ExternalUserIdAssociatedWithAddress(string,address,string,address,bytes,uint256)": EventFragment;
    "FundingGoalSet(address,address,uint256,uint256,bytes,uint256)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "InvoiceCompleteSet(address,uint256,bytes,uint256)": EventFragment;
    "InvoiceRequiredSet(address,bool,uint256,bytes,uint256)": EventFragment;
    "KYCRequiredSet(address,bool,uint256,bytes,uint256)": EventFragment;
    "OracleTransferred(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PayoutScheduleSet(address,address,uint256[],uint256,bytes,uint256)": EventFragment;
    "PayoutSet(address,address,uint256,uint256,bytes,uint256)": EventFragment;
    "SupportingDocumentsCompleteSet(address,uint256,bytes,uint256)": EventFragment;
    "SupportingDocumentsRequiredSet(address,bool,uint256,bytes,uint256)": EventFragment;
    "TierClaimed(address,address,bytes,uint256)": EventFragment;
    "TierWinnerSelected(address,string[],bytes,uint256)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BountyClosed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BountyCreated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ExternalUserIdAssociatedWithAddress"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FundingGoalSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InvoiceCompleteSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InvoiceRequiredSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "KYCRequiredSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OracleTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PayoutScheduleSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PayoutSet"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "SupportingDocumentsCompleteSet"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "SupportingDocumentsRequiredSet"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TierClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TierWinnerSelected"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface BountyClosedEventObject {
  bountyId: string;
  bountyAddress: string;
  organization: string;
  closer: string;
  bountyClosedTime: BigNumber;
  bountyType: BigNumber;
  data: string;
  version: BigNumber;
}
export type BountyClosedEvent = TypedEvent<
  [string, string, string, string, BigNumber, BigNumber, string, BigNumber],
  BountyClosedEventObject
>;

export type BountyClosedEventFilter = TypedEventFilter<BountyClosedEvent>;

export interface BountyCreatedEventObject {
  bountyId: string;
  organization: string;
  issuerAddress: string;
  bountyAddress: string;
  bountyMintTime: BigNumber;
  bountyType: BigNumber;
  data: string;
  version: BigNumber;
}
export type BountyCreatedEvent = TypedEvent<
  [string, string, string, string, BigNumber, BigNumber, string, BigNumber],
  BountyCreatedEventObject
>;

export type BountyCreatedEventFilter = TypedEventFilter<BountyCreatedEvent>;

export interface ExternalUserIdAssociatedWithAddressEventObject {
  newExternalUserId: string;
  newAddress: string;
  formerExternalUserId: string;
  formerAddress: string;
  data: string;
  version: BigNumber;
}
export type ExternalUserIdAssociatedWithAddressEvent = TypedEvent<
  [string, string, string, string, string, BigNumber],
  ExternalUserIdAssociatedWithAddressEventObject
>;

export type ExternalUserIdAssociatedWithAddressEventFilter =
  TypedEventFilter<ExternalUserIdAssociatedWithAddressEvent>;

export interface FundingGoalSetEventObject {
  bountyAddress: string;
  fundingGoalTokenAddress: string;
  fundingGoalVolume: BigNumber;
  bountyType: BigNumber;
  data: string;
  version: BigNumber;
}
export type FundingGoalSetEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, string, BigNumber],
  FundingGoalSetEventObject
>;

export type FundingGoalSetEventFilter = TypedEventFilter<FundingGoalSetEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface InvoiceCompleteSetEventObject {
  bountyAddress: string;
  bountyType: BigNumber;
  data: string;
  version: BigNumber;
}
export type InvoiceCompleteSetEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  InvoiceCompleteSetEventObject
>;

export type InvoiceCompleteSetEventFilter =
  TypedEventFilter<InvoiceCompleteSetEvent>;

export interface InvoiceRequiredSetEventObject {
  bountyAddress: string;
  invoiceRequired: boolean;
  bountyType: BigNumber;
  data: string;
  version: BigNumber;
}
export type InvoiceRequiredSetEvent = TypedEvent<
  [string, boolean, BigNumber, string, BigNumber],
  InvoiceRequiredSetEventObject
>;

export type InvoiceRequiredSetEventFilter =
  TypedEventFilter<InvoiceRequiredSetEvent>;

export interface KYCRequiredSetEventObject {
  bountyAddress: string;
  kycRequired: boolean;
  bountyType: BigNumber;
  data: string;
  version: BigNumber;
}
export type KYCRequiredSetEvent = TypedEvent<
  [string, boolean, BigNumber, string, BigNumber],
  KYCRequiredSetEventObject
>;

export type KYCRequiredSetEventFilter = TypedEventFilter<KYCRequiredSetEvent>;

export interface OracleTransferredEventObject {
  previousOracle: string;
  newOracle: string;
}
export type OracleTransferredEvent = TypedEvent<
  [string, string],
  OracleTransferredEventObject
>;

export type OracleTransferredEventFilter =
  TypedEventFilter<OracleTransferredEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PayoutScheduleSetEventObject {
  bountyAddress: string;
  payoutTokenAddress: string;
  payoutSchedule: BigNumber[];
  bountyType: BigNumber;
  data: string;
  version: BigNumber;
}
export type PayoutScheduleSetEvent = TypedEvent<
  [string, string, BigNumber[], BigNumber, string, BigNumber],
  PayoutScheduleSetEventObject
>;

export type PayoutScheduleSetEventFilter =
  TypedEventFilter<PayoutScheduleSetEvent>;

export interface PayoutSetEventObject {
  bountyAddress: string;
  payoutTokenAddress: string;
  payoutTokenVolume: BigNumber;
  bountyType: BigNumber;
  data: string;
  version: BigNumber;
}
export type PayoutSetEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, string, BigNumber],
  PayoutSetEventObject
>;

export type PayoutSetEventFilter = TypedEventFilter<PayoutSetEvent>;

export interface SupportingDocumentsCompleteSetEventObject {
  bountyAddress: string;
  bountyType: BigNumber;
  data: string;
  version: BigNumber;
}
export type SupportingDocumentsCompleteSetEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  SupportingDocumentsCompleteSetEventObject
>;

export type SupportingDocumentsCompleteSetEventFilter =
  TypedEventFilter<SupportingDocumentsCompleteSetEvent>;

export interface SupportingDocumentsRequiredSetEventObject {
  bountyAddress: string;
  supportingDocuments: boolean;
  bountyType: BigNumber;
  data: string;
  version: BigNumber;
}
export type SupportingDocumentsRequiredSetEvent = TypedEvent<
  [string, boolean, BigNumber, string, BigNumber],
  SupportingDocumentsRequiredSetEventObject
>;

export type SupportingDocumentsRequiredSetEventFilter =
  TypedEventFilter<SupportingDocumentsRequiredSetEvent>;

export interface TierClaimedEventObject {
  bountyAddress: string;
  claimant: string;
  data: string;
  version: BigNumber;
}
export type TierClaimedEvent = TypedEvent<
  [string, string, string, BigNumber],
  TierClaimedEventObject
>;

export type TierClaimedEventFilter = TypedEventFilter<TierClaimedEvent>;

export interface TierWinnerSelectedEventObject {
  bountyAddress: string;
  tierWinners: string[];
  data: string;
  version: BigNumber;
}
export type TierWinnerSelectedEvent = TypedEvent<
  [string, string[], string, BigNumber],
  TierWinnerSelectedEventObject
>;

export type TierWinnerSelectedEventFilter =
  TypedEventFilter<TierWinnerSelectedEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface OpenQV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OpenQV1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    VERSION_1(overrides?: CallOverrides): Promise<[BigNumber]>;

    addressToExternalUserId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    associateExternalIdToAddress(
      _externalUserId: PromiseOrValue<string>,
      _associatedAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    bountyAddressToBountyId(
      _bountyAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    bountyFactory(overrides?: CallOverrides): Promise<[string]>;

    bountyIdToAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    bountyIsOpen(
      _bountyId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    bountyType(
      _bountyId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    claimManager(overrides?: CallOverrides): Promise<[string]>;

    depositManager(overrides?: CallOverrides): Promise<[string]>;

    externalUserIdToAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getImplementation(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      _initialOracle: PromiseOrValue<string>,
      _bountyFactory: PromiseOrValue<string>,
      _depositManager: PromiseOrValue<string>,
      _claimManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    mintBounty(
      _bountyId: PromiseOrValue<string>,
      _organization: PromiseOrValue<string>,
      _initOperation: OpenQDefinitions.InitOperationStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBountyFactory(
      _bountyFactory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setClaimManager(
      _claimManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDepositManager(
      _depositManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFundingGoal(
      _bountyId: PromiseOrValue<string>,
      _fundingGoalToken: PromiseOrValue<string>,
      _fundingGoalVolume: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setInvoiceComplete(
      _bountyId: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setInvoiceRequired(
      _bountyId: PromiseOrValue<string>,
      _invoiceRequired: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setKycRequired(
      _bountyId: PromiseOrValue<string>,
      _kycRequired: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPayoutScheduleFixed(
      _bountyId: PromiseOrValue<string>,
      _payoutSchedule: PromiseOrValue<BigNumberish>[],
      _payoutTokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setSupportingDocumentsComplete(
      _bountyId: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setSupportingDocumentsRequired(
      _bountyId: PromiseOrValue<string>,
      _supportingDocumentsRequired: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTierWinner(
      _bountyId: PromiseOrValue<string>,
      _tier: PromiseOrValue<BigNumberish>,
      _winner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tierClaimed(
      _bountyId: PromiseOrValue<string>,
      _tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferOracle(
      _newOracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  VERSION_1(overrides?: CallOverrides): Promise<BigNumber>;

  addressToExternalUserId(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  associateExternalIdToAddress(
    _externalUserId: PromiseOrValue<string>,
    _associatedAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  bountyAddressToBountyId(
    _bountyAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  bountyFactory(overrides?: CallOverrides): Promise<string>;

  bountyIdToAddress(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  bountyIsOpen(
    _bountyId: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  bountyType(
    _bountyId: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claimManager(overrides?: CallOverrides): Promise<string>;

  depositManager(overrides?: CallOverrides): Promise<string>;

  externalUserIdToAddress(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  getImplementation(overrides?: CallOverrides): Promise<string>;

  initialize(
    _initialOracle: PromiseOrValue<string>,
    _bountyFactory: PromiseOrValue<string>,
    _depositManager: PromiseOrValue<string>,
    _claimManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  mintBounty(
    _bountyId: PromiseOrValue<string>,
    _organization: PromiseOrValue<string>,
    _initOperation: OpenQDefinitions.InitOperationStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  oracle(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBountyFactory(
    _bountyFactory: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setClaimManager(
    _claimManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDepositManager(
    _depositManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFundingGoal(
    _bountyId: PromiseOrValue<string>,
    _fundingGoalToken: PromiseOrValue<string>,
    _fundingGoalVolume: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setInvoiceComplete(
    _bountyId: PromiseOrValue<string>,
    _data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setInvoiceRequired(
    _bountyId: PromiseOrValue<string>,
    _invoiceRequired: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setKycRequired(
    _bountyId: PromiseOrValue<string>,
    _kycRequired: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPayoutScheduleFixed(
    _bountyId: PromiseOrValue<string>,
    _payoutSchedule: PromiseOrValue<BigNumberish>[],
    _payoutTokenAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setSupportingDocumentsComplete(
    _bountyId: PromiseOrValue<string>,
    _data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setSupportingDocumentsRequired(
    _bountyId: PromiseOrValue<string>,
    _supportingDocumentsRequired: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTierWinner(
    _bountyId: PromiseOrValue<string>,
    _tier: PromiseOrValue<BigNumberish>,
    _winner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tierClaimed(
    _bountyId: PromiseOrValue<string>,
    _tier: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferOracle(
    _newOracle: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    VERSION_1(overrides?: CallOverrides): Promise<BigNumber>;

    addressToExternalUserId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    associateExternalIdToAddress(
      _externalUserId: PromiseOrValue<string>,
      _associatedAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    bountyAddressToBountyId(
      _bountyAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    bountyFactory(overrides?: CallOverrides): Promise<string>;

    bountyIdToAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    bountyIsOpen(
      _bountyId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    bountyType(
      _bountyId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimManager(overrides?: CallOverrides): Promise<string>;

    depositManager(overrides?: CallOverrides): Promise<string>;

    externalUserIdToAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    getImplementation(overrides?: CallOverrides): Promise<string>;

    initialize(
      _initialOracle: PromiseOrValue<string>,
      _bountyFactory: PromiseOrValue<string>,
      _depositManager: PromiseOrValue<string>,
      _claimManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    mintBounty(
      _bountyId: PromiseOrValue<string>,
      _organization: PromiseOrValue<string>,
      _initOperation: OpenQDefinitions.InitOperationStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    oracle(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setBountyFactory(
      _bountyFactory: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setClaimManager(
      _claimManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDepositManager(
      _depositManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFundingGoal(
      _bountyId: PromiseOrValue<string>,
      _fundingGoalToken: PromiseOrValue<string>,
      _fundingGoalVolume: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setInvoiceComplete(
      _bountyId: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setInvoiceRequired(
      _bountyId: PromiseOrValue<string>,
      _invoiceRequired: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setKycRequired(
      _bountyId: PromiseOrValue<string>,
      _kycRequired: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPayoutScheduleFixed(
      _bountyId: PromiseOrValue<string>,
      _payoutSchedule: PromiseOrValue<BigNumberish>[],
      _payoutTokenAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setSupportingDocumentsComplete(
      _bountyId: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setSupportingDocumentsRequired(
      _bountyId: PromiseOrValue<string>,
      _supportingDocumentsRequired: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setTierWinner(
      _bountyId: PromiseOrValue<string>,
      _tier: PromiseOrValue<BigNumberish>,
      _winner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    tierClaimed(
      _bountyId: PromiseOrValue<string>,
      _tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOracle(
      _newOracle: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;

    "BountyClosed(string,address,string,address,uint256,uint256,bytes,uint256)"(
      bountyId?: null,
      bountyAddress?: null,
      organization?: null,
      closer?: null,
      bountyClosedTime?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): BountyClosedEventFilter;
    BountyClosed(
      bountyId?: null,
      bountyAddress?: null,
      organization?: null,
      closer?: null,
      bountyClosedTime?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): BountyClosedEventFilter;

    "BountyCreated(string,string,address,address,uint256,uint256,bytes,uint256)"(
      bountyId?: null,
      organization?: null,
      issuerAddress?: null,
      bountyAddress?: null,
      bountyMintTime?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): BountyCreatedEventFilter;
    BountyCreated(
      bountyId?: null,
      organization?: null,
      issuerAddress?: null,
      bountyAddress?: null,
      bountyMintTime?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): BountyCreatedEventFilter;

    "ExternalUserIdAssociatedWithAddress(string,address,string,address,bytes,uint256)"(
      newExternalUserId?: null,
      newAddress?: null,
      formerExternalUserId?: null,
      formerAddress?: null,
      data?: null,
      version?: null
    ): ExternalUserIdAssociatedWithAddressEventFilter;
    ExternalUserIdAssociatedWithAddress(
      newExternalUserId?: null,
      newAddress?: null,
      formerExternalUserId?: null,
      formerAddress?: null,
      data?: null,
      version?: null
    ): ExternalUserIdAssociatedWithAddressEventFilter;

    "FundingGoalSet(address,address,uint256,uint256,bytes,uint256)"(
      bountyAddress?: null,
      fundingGoalTokenAddress?: null,
      fundingGoalVolume?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): FundingGoalSetEventFilter;
    FundingGoalSet(
      bountyAddress?: null,
      fundingGoalTokenAddress?: null,
      fundingGoalVolume?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): FundingGoalSetEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "InvoiceCompleteSet(address,uint256,bytes,uint256)"(
      bountyAddress?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): InvoiceCompleteSetEventFilter;
    InvoiceCompleteSet(
      bountyAddress?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): InvoiceCompleteSetEventFilter;

    "InvoiceRequiredSet(address,bool,uint256,bytes,uint256)"(
      bountyAddress?: null,
      invoiceRequired?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): InvoiceRequiredSetEventFilter;
    InvoiceRequiredSet(
      bountyAddress?: null,
      invoiceRequired?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): InvoiceRequiredSetEventFilter;

    "KYCRequiredSet(address,bool,uint256,bytes,uint256)"(
      bountyAddress?: null,
      kycRequired?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): KYCRequiredSetEventFilter;
    KYCRequiredSet(
      bountyAddress?: null,
      kycRequired?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): KYCRequiredSetEventFilter;

    "OracleTransferred(address,address)"(
      previousOracle?: PromiseOrValue<string> | null,
      newOracle?: PromiseOrValue<string> | null
    ): OracleTransferredEventFilter;
    OracleTransferred(
      previousOracle?: PromiseOrValue<string> | null,
      newOracle?: PromiseOrValue<string> | null
    ): OracleTransferredEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "PayoutScheduleSet(address,address,uint256[],uint256,bytes,uint256)"(
      bountyAddress?: null,
      payoutTokenAddress?: null,
      payoutSchedule?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): PayoutScheduleSetEventFilter;
    PayoutScheduleSet(
      bountyAddress?: null,
      payoutTokenAddress?: null,
      payoutSchedule?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): PayoutScheduleSetEventFilter;

    "PayoutSet(address,address,uint256,uint256,bytes,uint256)"(
      bountyAddress?: null,
      payoutTokenAddress?: null,
      payoutTokenVolume?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): PayoutSetEventFilter;
    PayoutSet(
      bountyAddress?: null,
      payoutTokenAddress?: null,
      payoutTokenVolume?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): PayoutSetEventFilter;

    "SupportingDocumentsCompleteSet(address,uint256,bytes,uint256)"(
      bountyAddress?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): SupportingDocumentsCompleteSetEventFilter;
    SupportingDocumentsCompleteSet(
      bountyAddress?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): SupportingDocumentsCompleteSetEventFilter;

    "SupportingDocumentsRequiredSet(address,bool,uint256,bytes,uint256)"(
      bountyAddress?: null,
      supportingDocuments?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): SupportingDocumentsRequiredSetEventFilter;
    SupportingDocumentsRequiredSet(
      bountyAddress?: null,
      supportingDocuments?: null,
      bountyType?: null,
      data?: null,
      version?: null
    ): SupportingDocumentsRequiredSetEventFilter;

    "TierClaimed(address,address,bytes,uint256)"(
      bountyAddress?: null,
      claimant?: null,
      data?: null,
      version?: null
    ): TierClaimedEventFilter;
    TierClaimed(
      bountyAddress?: null,
      claimant?: null,
      data?: null,
      version?: null
    ): TierClaimedEventFilter;

    "TierWinnerSelected(address,string[],bytes,uint256)"(
      bountyAddress?: null,
      tierWinners?: null,
      data?: null,
      version?: null
    ): TierWinnerSelectedEventFilter;
    TierWinnerSelected(
      bountyAddress?: null,
      tierWinners?: null,
      data?: null,
      version?: null
    ): TierWinnerSelectedEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
  };

  estimateGas: {
    VERSION_1(overrides?: CallOverrides): Promise<BigNumber>;

    addressToExternalUserId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    associateExternalIdToAddress(
      _externalUserId: PromiseOrValue<string>,
      _associatedAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    bountyAddressToBountyId(
      _bountyAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bountyFactory(overrides?: CallOverrides): Promise<BigNumber>;

    bountyIdToAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bountyIsOpen(
      _bountyId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bountyType(
      _bountyId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimManager(overrides?: CallOverrides): Promise<BigNumber>;

    depositManager(overrides?: CallOverrides): Promise<BigNumber>;

    externalUserIdToAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _initialOracle: PromiseOrValue<string>,
      _bountyFactory: PromiseOrValue<string>,
      _depositManager: PromiseOrValue<string>,
      _claimManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    mintBounty(
      _bountyId: PromiseOrValue<string>,
      _organization: PromiseOrValue<string>,
      _initOperation: OpenQDefinitions.InitOperationStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBountyFactory(
      _bountyFactory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setClaimManager(
      _claimManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDepositManager(
      _depositManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFundingGoal(
      _bountyId: PromiseOrValue<string>,
      _fundingGoalToken: PromiseOrValue<string>,
      _fundingGoalVolume: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setInvoiceComplete(
      _bountyId: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setInvoiceRequired(
      _bountyId: PromiseOrValue<string>,
      _invoiceRequired: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setKycRequired(
      _bountyId: PromiseOrValue<string>,
      _kycRequired: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPayoutScheduleFixed(
      _bountyId: PromiseOrValue<string>,
      _payoutSchedule: PromiseOrValue<BigNumberish>[],
      _payoutTokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setSupportingDocumentsComplete(
      _bountyId: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setSupportingDocumentsRequired(
      _bountyId: PromiseOrValue<string>,
      _supportingDocumentsRequired: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTierWinner(
      _bountyId: PromiseOrValue<string>,
      _tier: PromiseOrValue<BigNumberish>,
      _winner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tierClaimed(
      _bountyId: PromiseOrValue<string>,
      _tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOracle(
      _newOracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    VERSION_1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addressToExternalUserId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    associateExternalIdToAddress(
      _externalUserId: PromiseOrValue<string>,
      _associatedAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    bountyAddressToBountyId(
      _bountyAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bountyFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bountyIdToAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bountyIsOpen(
      _bountyId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bountyType(
      _bountyId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    externalUserIdToAddress(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getImplementation(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _initialOracle: PromiseOrValue<string>,
      _bountyFactory: PromiseOrValue<string>,
      _depositManager: PromiseOrValue<string>,
      _claimManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    mintBounty(
      _bountyId: PromiseOrValue<string>,
      _organization: PromiseOrValue<string>,
      _initOperation: OpenQDefinitions.InitOperationStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBountyFactory(
      _bountyFactory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setClaimManager(
      _claimManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDepositManager(
      _depositManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFundingGoal(
      _bountyId: PromiseOrValue<string>,
      _fundingGoalToken: PromiseOrValue<string>,
      _fundingGoalVolume: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setInvoiceComplete(
      _bountyId: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setInvoiceRequired(
      _bountyId: PromiseOrValue<string>,
      _invoiceRequired: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setKycRequired(
      _bountyId: PromiseOrValue<string>,
      _kycRequired: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPayoutScheduleFixed(
      _bountyId: PromiseOrValue<string>,
      _payoutSchedule: PromiseOrValue<BigNumberish>[],
      _payoutTokenAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setSupportingDocumentsComplete(
      _bountyId: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setSupportingDocumentsRequired(
      _bountyId: PromiseOrValue<string>,
      _supportingDocumentsRequired: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTierWinner(
      _bountyId: PromiseOrValue<string>,
      _tier: PromiseOrValue<BigNumberish>,
      _winner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tierClaimed(
      _bountyId: PromiseOrValue<string>,
      _tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOracle(
      _newOracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
