/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAtomicBounty } from "./IAtomicBounty";
export type { IBounty } from "./IBounty";
export type { IBountyCore } from "./IBountyCore";
export type { IOngoingBounty } from "./IOngoingBounty";
export type { ITieredBounty } from "./ITieredBounty";
export type { ITieredFixedBounty } from "./ITieredFixedBounty";
export type { ITieredPercentageBounty } from "./ITieredPercentageBounty";
